title: kahsing.pang
logo: /assets/img/logo.png
profile: /assets/img/profile.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
sass:
    style: :compressed