title: Sean Pang
logo: /assets/img/signage.png
profile: /assets/img/profile.png
author: Sean Pang
description: kahsing.pang @The Sanctuary.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
paginate: 3
paginate_path: "/pages/story/page:num/"
sass:
    style: :compressed
