title: kahsing.pang
logo: /assets/img/logo.png
profile: /assets/img/profile.png
author: Sean Pang
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
paginate: 3
paginate_path: "/pages/story/page:num/"
sass:
    style: :compressed
